### ISSUE TITLE
Update Output + Instance

### ISSUE THREAD

**Issue by antoinepagnien** [loicbourgois/ig2i-le4-poo-2018-projet-poower-rangers#16]
- Ajouter le passage du modèle objet au fichier solution
- Alimenter l'algo avec les fichiers d'instances
- Récupérer la sortie de l'algo pour générer le fichier solution

**Comment by loicbourgois** [comment]
> Alimenter l'algo avec les fichiers d'instances

@antoinepagnien Pourquoi ce serait dans Output ?

C'est plutôt dans Instance que ça se passe, non ?

**Comment by antoinepagnien** [comment]
Oui, j'avais pas mis à jour le titre

**Comment by loicbourgois** [comment]
Si c'est à différents endroits, c'est mieux de faire différente Issues. 

Là je pense que chacun de tes 3 points devrait être une issue.

**Comment by loicbourgois** [comment]
> Alimenter l'algo avec les fichiers d'instances

C'est déjà le cas : https://github.com/loicbourgois/ig2i-le4-poo-2018-projet-poower-rangers/blob/master/src/metier/Instance.java#L333
